AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Instance for Java App

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: my-demo-keypair.pem        # Replace this
      ImageId: ami-0e449927258d45bc4      # Amazon Linux 2 (update based on region)
      SecurityGroups:
        - default
      Tags:
        - Key: Name
          Value: MavenAppEC2
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y java-1.8.0-openjdk
          mkdir -p /opt/mavenapp
