pipeline {
    agent any
     tools {
        maven 'M3'   // 👈 Tells Jenkins to use the Maven tool named "M3"
    }

    stages {
        stage('Git Checkout Code') {
            steps {
                git url: 'https://github.com/prabareddy1996/simple-java-maven-app.git', branch: 'master'
            }
        }

        stage('Build with Maven') {
            steps {
                bat 'mvn clean install'
            }
        }
	}
}
